### ISSUE TITLE
Serialization bug

### ISSUE THREAD

**Issue by FaerHack** [eyalz800/zpp_bits#168] opened 2024-07-11 18:23 UTC
For some reason, when I try to serialize const and non-const structures, I get different results. For instance, the following example outputs "18 10". Is it expected behavior?

```
struct TEST_STRUCT
{
	int a;
	std::string b;
	std::string c;
};

auto SeirializeNormal(
	_In_ auto& Object)
{
	auto [data, out] = zpp::bits::data_out<char>();
	out(Object);

	return data;
}

auto SeirializeConst(
	_In_ const auto& Object)
{
	auto [data, out] = zpp::bits::data_out<char>();
	out(Object);

	return data;
}

int main()
{
	TEST_STRUCT Struct{ 1, "123", "456" };

	auto data = SeirializeNormal(Struct);
	auto data1 = SeirializeConst(Struct);

	printf("%i %i\n", data.size(), data1.size());

	return 0;
}
```

**Comment by eyalz800** [comment] 2024-07-11 21:14
Is this msvc? Check if it’s the same as this https://github.com/eyalz800/zpp_bits/issues/164

**Comment by FaerHack** [comment] 2024-07-12 06:22
yes, it's msvc, and it seems to be the same issue as the one you mentioned

**Comment by eyalz800** [comment] 2024-07-12 08:08
We need them to fix the bug

**Comment by eyalz800** [comment] 2024-07-21 09:12
Closing as duplicate of #164

**Closed by eyalz800** 2024-07-21 09:12 UTC
