### ISSUE TITLE
Internal Compiler Error - MSVC Latest (14.34.31933)

### ISSUE THREAD

**Issue by SenseOnline** [eyalz800/zpp_bits#99] opened 2022-11-11 11:45 UTC
Microsoft recently released an update to VS2022 that broke compilation for zpp_bits

Reproduction here (14.34.31931-Pre):
https://godbolt.org/z/szx4PTMM8

Is there any workarounds or fixes? 

I have not opened a ticket with microsoft since I would be unable to provide a minimal reproduction but it may be worth looking into.

**Comment by eyalz800** [comment] 2022-11-12 09:10
I will try to play with it but it seems they did provide a hint that it’s on line 238 where the code checks if there is a serialize member function in the struct or outside

**Comment by eyalz800** [comment] 2022-11-15 16:05
By the way what is the relation of this version with the one mentioned here - https://github.com/eyalz800/zpp_bits/issues/83#issuecomment-1313989949

**Comment by RT222** [comment] 2022-11-16 00:31
I tried it on my end, and I can confirm that your library fails to build on Visual Studio 17.4 an 17.4.1.

> By the way what is the relation of this version with the one mentioned here - [#83 (comment)](https://github.com/eyalz800/zpp_bits/issues/83#issuecomment-1313989949)

It's the same, MSVC 14.34 ships with Visual Studio 17.4. You can find this information here : https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering

**Comment by SenseOnline** [comment] 2022-11-16 03:32
I did a little digging and it *seemingly* seems like MSVC doesn't like `decltype(serialize(item))` when it fails to find anything. 

Changing the function to what's shown below, adding a check to remove instantiation, allows MSVC on compiler explorer to compile. Also tested to compile fine on clang and gcc. Perhaps something like this could be used, albeit ugly.
```
template <typename Type>
constexpr static auto has_adl_serialize()
{
    return requires (Type&& item) {
        serialize(item);
    };
}
template <typename Type>
constexpr static auto adl_passthrough(Type&& item)
{
    if constexpr (has_adl_serialize<Type>())
        return serialize(item);
    return void();
}

template <typename Type, typename Archive>
constexpr static auto has_serialize()
{
    return requires
    {
        requires std::same_as<
            typename std::remove_cvref_t<Type>::serialize,
            members<std::remove_cvref_t<Type>::serialize::value>>;
    }
    || requires(Type && item)
    {
        requires std::same_as<
            std::remove_cvref_t<decltype(adl_passthrough(item))>,
            members<std::remove_cvref_t<decltype(adl_passthrough(item))>::value>>;
    }
    || requires
    {
        requires std::same_as<
            typename std::remove_cvref_t<Type>::serialize,
            protocol<std::remove_cvref_t<Type>::serialize::value,
                        std::remove_cvref_t<Type>::serialize::members>>;
    }
    ||  requires(Type && item)
    {
        requires std::same_as<
            std::remove_cvref_t<decltype(adl_passthrough(item))>,
            protocol<
                std::remove_cvref_t<decltype(adl_passthrough(item))>::value,
                std::remove_cvref_t<decltype(adl_passthrough(
                    item))>::members>>;
    }
    || requires(Type && item, Archive && archive)
    {
        std::remove_cvref_t<Type>::serialize(archive, item);
    }
    || requires(Type && item, Archive && archive)
    {
        serialize(archive, item);
    };
}
```

However, when I tried a small example,
```
template <typename Type>
constexpr static auto example(Type&&)
{
    return requires (Type&& item) {
        requires std::same_as<std::remove_cvref_t<decltype(serialize(item))>, void>;
    };
}
void foo(void)
{
    example(std::vector<int>{});
}
```
Compiles just fine. Either there is more needed to trigger the compiler bug or it is elsewhere.

**Comment by eyalz800** [comment] 2022-11-16 07:54
@SenseOnline with the workaround that you found can you work now without changing the library code? I guess that we need to file a bug or something if we are able to isolate the issue as well, but trying to free some time on my end

**Comment by SenseOnline** [comment] 2022-11-16 10:26
Yes, I will be able to work around it without changing the library code.

**Comment by mapron** [comment] 2023-01-03 01:20
Well, after CppCon talk I tried to  integrate this project into my projects. But for me MSVC is the main platform, so kinda sad I can' use it. I could not found a test which is compile with latest MSVC.

Any another workarounds (with probably a lot of hand writing) would be nice for now

**Comment by eyalz800** [comment] 2023-01-03 08:42
@mapron I believe we need to (or I need to) create a minimal example of the issue with msvc and submit that. It was tested on MSVC and there are people that confirmed it in some of the closed issues, but it gets regressed probably as MSVC is updating the code.

**Comment by eyalz800** [comment] 2023-01-03 08:48
Can you take a look a this - https://godbolt.org/z/avEv8ovce

**Comment by Notallthatevil** [comment] 2023-01-03 14:37
For a workaround on MSVC. I have had success commenting out this line of code in access::has_serialize
         `|| requires(Type && item)
         {
            requires std::same_as<
               std::remove_cvref_t<decltype(serialize(item))>,
                  members<std::remove_cvref_t<decltype(serialize(
                     item))>::value>>;
         }
         || requires(Type && item)
         {
            requires std::same_as<
               std::remove_cvref_t<decltype(serialize(item))>,
                  protocol<
                  std::remove_cvref_t<decltype(serialize(item))>::value,
                  std::remove_cvref_t<decltype(serialize(
                     item))>::members>>;
         }`

And this one in access::has_protocol
`requires(Type && item)
         {
            requires std::same_as<
               std::remove_cvref_t<decltype(serialize(item))>,
                  protocol<
                  std::remove_cvref_t<decltype(serialize(item))>::value,
                  std::remove_cvref_t<decltype(serialize(
                     item))>::members>>;
         }`

Not sure exactly what the problem is, but apparently MSVC does not like the decltype(serialize(item))

**Comment by eyalz800** [comment] 2023-01-03 14:40
@no

**Comment by eyalz800** [comment] 2023-01-03 14:41
Accidentally clicked the close with comment button - 

@Notallthatevil this is with the 19.34 or with 19.33? For me the above godbolt link compiles with 19.33

**Comment by mapron** [comment] 2023-01-04 07:26
@eyalz800  I read the whole thread, I understand it works on previous release. (and proper report must be filed). I tried to create minimal reproducer and I failed (well, obviously), because I'm not an author and it's hard for me to 'reduce smth smth and it still compile'.
Downgrading a compiler is not an option for me or my clients :) so I will wait until it's fixed.

**Comment by SenseOnline** [comment] 2023-01-16 02:27
> Can you take a look a this - https://godbolt.org/z/avEv8ovce - looks like on this compiler version it works @SenseOnline @mapron

Apologies for the late reply, I am aware that it works on previous versions. 

Also sorry if my previous comments were misleading but I'm currently using the workaround where I've inserted the two helper functions stated previously and replaced all instances of `decltype(serialize(item))` with the helper function variation in the two functions `access::has_serialize` and `access::has_protocol`. 
Had no problems with that thus far.

**Comment by eyalz800** [comment] 2023-01-18 09:03
@SenseOnline that can be a nice workaround, I'll check it hopefully during the weekend and if it fixes it I'll push an update.

**Comment by mapron** [comment] 2023-01-18 10:40
@eyalz800  Good luck , I will stay tuned.

**Comment by eyalz800** [comment] 2023-01-20 14:20
Please check #104, here is the godbolt: https://godbolt.org/z/hf3ce1d5a
It seems to work around the ICE issue.

@mapron / @SenseOnline / @Notallthatevil / @RT222 can you comment if this works for you, so we can close this issue?

**Comment by mapron** [comment] 2023-01-23 09:36
@eyalz800   I can confirm code https://github.com/fraillt/cpp_serializers_benchmark now works with your patch and vs2022, thanks. 
That's all I need for the start.

**Comment by eyalz800** [comment] 2023-01-23 21:19
Ok closing the issue - please reopen if you see the issue again - ideally I will need to get time to reproduce with minimal example to submit a bug to visual studio but I’m not able to do that now

**Closed by eyalz800** 2023-01-23 21:19 UTC
